typography_spectrum: 0.28726
color:
  brandColors:
    - '#003f86'
    - '#fbf9fa'
    - '#00b4d5'
    - '#548100'
    - '#b99c70'
  brandStrength: 0.375
  lightness: 0.8125
  saturation: 0.125
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: Kilowatts
cta:
  domain: null
  bucket: null
  version: null
favicon: null
description: Utility Advisor
purpose: []
