name: Glen in Majuro
favicon: null
layout_spectrum: 1
typography_spectrum: 0.719524561194703
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#003f86'
    - '#fbf9fa'
    - '#00b4d5'
    - '#548100'
    - '#b99c70'
  brandStrength: 0.375
  lightness: 0.8125
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
